{
  "name": "SimpleBotz",
  "version": "5.0.0",
  "description": "WhatsApp Bot By Skyzopedia",
  "main": "start.js",
  "type": "commonjs",
  "scripts": {
    "start": "node --no-deprecation start.js"
  },
  "keywords": [
    "baileys",
    "whiskeysockets/baileys",
    "2024",
    "2025",
    "skyzopedia"
  ],
  "author": "Skyzopedia",
  "license": "MIT",
  "dependencies": {
    "@hapi/boom": "^10.0.0",
    "@whiskeysockets/baileys": "npm:@fizzxydev/baileys-pro@8.3.3",
    "awesome-phonenumber": "^4.4.0",
    "axios": "^0.24.0",
    "canvafy": "^7.2.0",
    "cfonts": "^3.3.0",
    "chalk": "^4.1.2",
    "cheerio": "^1.0.0-rc.10",
    "child_process": "^1.0.2",
    "crypto": "^1.0.1",
    "file-type": "^16.5.3",
    "filesize": "^10.0.7",
    "fluent-ffmpeg": "^2.1.2",
    "form-data": "^4.0.0",
    "fs": "^0.0.1-security",
    "human-readable": "^0.2.1",
    "jimp": "^0.16.13",
    "js-confuser": "^1.7.3",
    "link-preview-js": "^3.0.4",
    "moment-timezone": "^0.5.43",
    "mongoose": "^7.3.4",
    "node-fetch": "^2.6.1",
    "node-gtts": "^2.0.2",
    "node-os-utils": "^1.3.7",
    "node-upload-images": "^1.0.1",
    "node-webpmux": "^3.1.7",
    "os": "^0.1.2",
    "path": "^0.12.7",
    "perf_hooks": "^0.0.1",
    "performance-now": "^2.1.0",
    "pino": "^9.4.0",
    "process": "^0.11.10",
    "qrcode": "^1.5.4",
    "qrcode-reader": "^1.0.4",
    "ruhend-scraper": "^8.2.0",
    "ssh2": "^1.15.0",
    "stream": "^0.0.3",
    "translate-google-api": "^1.0.4",
    "util": "^0.12.5",
    "yargs": "^17.6.2",
    "yt-search": "^2.10.4"
  }
}
